# Generated by Django 4.0.6 on 2022-07-06 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=32, verbose_name='Name')),
                ('Account_Number', models.CharField(max_length=9, verbose_name='Account_Number')),
                ('Balance', models.FloatField(verbose_name='Balance')),
                ('Address', models.CharField(max_length=100, verbose_name='Address')),
                ('Mobile_Number', models.CharField(max_length=10, verbose_name='Mobile_Number')),
            ],
        ),
    ]
