# Generated by Django 4.0.6 on 2022-07-17 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BankingSystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sender', models.CharField(max_length=32, verbose_name='Sender')),
                ('Receiver', models.CharField(max_length=32, verbose_name='Receiver')),
                ('Amount', models.FloatField(verbose_name='Amount')),
            ],
        ),
    ]
